Repository torrust/torrust-website, pull requests merged in 2024-05, with the labels that each got.

#174 Update dependencies
  package-lock.json
Labels: dependencies

#178 Page for tags in blog post, share button, and updated packages
  package-lock.json
  package.json
  src/lib/components/atoms/Tag.story.svelte
  src/lib/components/atoms/Tag.svelte
  src/lib/components/molecules/BlogPostCard.svelte
  src/lib/components/molecules/FeatureCard.svelte
  src/lib/components/molecules/ProjectCard.svelte
  src/lib/components/singletons/ContributionCard.svelte
  src/lib/components/singletons/ShareButton.svelte
  src/lib/components/singletons/ShareUrl.svelte
  src/routes/(blog-article)/+layout.svelte
  src/routes/tags/+layout.svelte
  src/routes/tags/[tagId]/+page.server.ts
  src/routes/tags/[tagId]/+page.svelte
Labels: Enhancement / Feature Request

#183 Update dependencies
  package-lock.json
Labels: dependencies

#188 Review article: How To Set Up a Local Demo
  src/routes/(blog-article)/how-to-run-a-local-demo/+page.md
Labels: blog post

#189 Review article: Deploying Torrust To Production
  src/routes/(blog-article)/deploying-torrust-to-production/+page.md
Labels: blog post

#197 Update dependencies
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  svelte.config.js
Labels: dependencies
